#!/usr/bin/env bash
# install and configure a load balancer
sudo apt-get update
sudo apt-get -y install haproxy
echo "frontend apache_front
        bind *:80
        mode               http
        default_backend    anthony_backend" >> /etc/haproxy/haproxy.cfg

echo "backend anthony_backend
        balance            roundrobin
        server             3588-web-01 35.237.143.24:80 check
        server             3588-web-02 34.73.58.201:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
