#!/usr/bin/env bash
# install nginx and configure the server to listen on port 80
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
sed -i 's/listen 8080 default_server;/listen 80 default_server/g' /etc/nginx/sites-enabled/default
service nginx restart
