#!/usr/bin/env bash
# install nginx and configure the server to listen on port 80
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
sed -i -e 's/8080/80/g' /etc/nginx/sites-enabled/default
service nginx restart
