#!/usr/bin/env bash
# This script displays a list of currently running processes
# The 'f' option tells ps to display a tree view of parent to child processes:
# The 'a' option tells ps to display the processes of all users. Only the processes 
# -that not associated with a terminal and processes of group leaders are not shown.
# The 'u' stands for a user-oriented format that provides detailed information about the processes.
# The x option instructs ps to list the processes without a controlling terminal.
ps -faux
