#!/usr/bin/env bash
# this script change the localhost ip 127.0.0.1 to 127.0.0.2
# and create an ip of facebook
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
sed -i '1 a 8.8.8.8 \t facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
